#------------------------
# 常用的配置
#------------------------

# 响应压缩
server:
  compression:
    enabled: true
  mime-types: 
    - application/json
    - application/xml
    - application/javascript
    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
  min-response-size: 2048
   
# logback日志
logging:
  config: classpath:logback.xml

spring:
  application:
    name: Javaweb开发者社区
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
      location: D:\\temp
      file-size-threshold: 10MB
  mvc:
    favicon:
      enabled: true
    date-format: yyyy-MM-dd HH:mm:ss
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/static/
      - file:${system.local.image-folder}
  cache:
    type: JCACHE
  freemarker:
    enabled: true
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    content-type: text/html
    # 开发环境模版,模板引擎不缓存
    cache: false
    template-loader-path:
      - classpath:/templates/
    charset: UTF-8
    template-encoding: UTF-8
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      # 模板引擎检测模板变化时间差
      # template_update_delay: 0
      
      
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mapper/**/*-mapper.xml
    - classpath:mapper/**/*-mapper-ext.xml

#------------------------
# 不同环境配置
#------------------------


server:
  port: 443
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:ssl/localhost.keystore
    key-store-type: PKCS12
    key-store-password: 123456
  http2:
    enabled: true
    
system:
  host: localhost
  session:
    key: 0C1B55C2E72C11E8B06700163E084A12
  local:
    image-folder: D:\\static

aliyun:
  oss:
    access-key: 
    secret-key: 
    endpoint: 
    bucket: 
    prefix: https://${aliyun.oss.bucket}.${aliyun.oss.endpoint}

tencent:
  captcha:
    verify-url: https://ssl.captcha.qq.com/ticket/verify
    account:
      app-id: 
      app-secret-key: 
    forum:
      app-id: 
      app-secret-key: 0n36auU6HzzaGJwHRynKvWg**
    email:
      app-id: 
      app-secret-key: 

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaweb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: root
    initialSize: 2
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    jcache:
      config: classpath:ehcache/ehcache-dev.xml
  mail:
    host: smtp.exmail.qq.com
    username: 
    password: 
    sender: Javaweb开发者社区
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
